spring:
  data:
    rest:
      base-path: /api
    mongodb:
      uri: mongodb+srv://reli:1234@cluster0-h4s7l.azure.mongodb.net/test?retryWrites=true&w=majority
management:
  endpoints:
    web:
      exposure:
        include=*: